### ISSUE TITLE
Secret(s) found: 2 - [Product Security - Secret Scanning]

### ISSUE THREAD

**Issue by nhamzi** [LMS-Community/squeezeos#2]
This is automated issue created by Logitech Secret Scanner v1.0 - Nabil Hamzi

It seems that information looking like a secret (password, token, credentials, ...) has been identified in this github repository.
We should avoid as much as possible to store secrets in Github code repository. Github has an 'encrypted secrets' feature for this.
Please react on this thread with @nhamzi for any question.

Here are the findings, SecretLink contains the link to the sensitive value to be renewed, refreshed and deleted.

SecretLink=https://github.com/Logitech/squeezeos/blob/d15e5fdc094b445d05bc07df64bed1d1245d62ca/src/imx35/patches-no-preempt/kernel.org/patch-2.6.26.8#L2890-L2890
SecretLink=https://github.com/Logitech/squeezeos/blob/d433a2b1a957cca1782afeba5f27b22267f2b336/poky/meta/packages/eds/eds-dbus-2.20.0/oh-contact.patch#L20-L20

**Comment by etissotdupont** [comment]
@nhamzi , this is (I believe) old FW for the Squeezebox firmware. I think the first one is a false positive and the second is... I don't know.
@mherger , what should we do? delete the repo? If we start deleting stuff, it becomes useless... and we're certainly not "fixing" it.

**Comment by terual** [comment]
Both are false positives.

**Comment by mherger** [comment]
Hehe... the second is part of the Base64 encoded Ximian logo 😂. Definitely false positives.
